# Generated by Django 5.2.7 on 2025-10-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchitem',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='watchitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='watchitem',
            name='ticker',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.RemoveField(
            model_name='watchitem',
            name='user',
        ),
    ]
